### ISSUE TITLE
Suggestion: Move `WOOCO_Beanstream` class definition to its own file

### ISSUE THREAD

**Issue by kienstra** [calvincanas/wootastic-beanstream#1]
## Background
The class `WOOCO_Beanstream` is defined just how the WooCommerce docs [suggest](https://woocommerce.com/document/payment-gateway-api/#section-2).

https://github.com/calvincanas/wootastic-beanstream/blob/fdb70e54a6f0e70d4f8457259285e25517ff7bea/wootastic-beanstream.php#L31-L41

But I think it's strange to have a class definition in a file that has other functions.

## Suggestion
It'd be good to move the definition of [WOOCO_Beanstream](https://github.com/calvincanas/wootastic-beanstream/blob/fdb70e54a6f0e70d4f8457259285e25517ff7bea/wootastic-beanstream.php#L41) to its own file in `includes/`.

Then, the function [wooco_beanstream()](https://github.com/calvincanas/wootastic-beanstream/blob/fdb70e54a6f0e70d4f8457259285e25517ff7bea/wootastic-beanstream.php#L36) could `include` that file.

A more advanced approach would be using the Composer [psr-4 autoloader](https://github.com/studiopress/genesis-custom-blocks/blob/03605dd5aaf20945b019c2b496fa5185c1f91409/composer.json#L25-L28), but that could be overkill for a plugin with 1 class.

**Comment by calvincanas** [comment]
Thanks for the suggestion, I went ahead and did that as you can see on this commit: cddc95fdafd82115ecac2d71893fe0b4b5569b18

**Comment by kienstra** [comment]
@calvincanas, nice, https://github.com/calvincanas/wootastic-beanstream/commit/cddc95fdafd82115ecac2d71893fe0b4b5569b18 looks good!
