### ISSUE TITLE
Sanitization of `$_POST['wooco_beanstream-card-expiry']`

### ISSUE THREAD

**Issue by kienstra** [calvincanas/wootastic-beanstream#2]
## Background
There's no sanitization or validation now:

https://github.com/calvincanas/wootastic-beanstream/blob/fdb70e54a6f0e70d4f8457259285e25517ff7bea/wootastic-beanstream.php#L176-L177

## Suggestion
Maybe [filter_input()](https://github.com/studiopress/genesis-custom-blocks/search?q=filter_input) would be good here, depending on what value it expects.

Security and performance are the biggest things WP agencies typically look for.

**Comment by calvincanas** [comment]
For valid format of the value it should be: 01/2021 since it is a credit card's expiration date.
